name: Tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  HUSKY: '0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - run: pnpm lint --fix
      - run: pnpm prettier
      - run: pnpm build
      - name: correct vercel/ncc crlf output
        run: sed -i 's/\x0D$//' ./dist/index.js
      - name: check for unstaged files
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: .github/no-unstaged-files.sh
